language:        node_js
sudo:            required
os:
  - linux
node_js:
  - "10.6.0"
services:
  - docker

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker run -d -p 5984:5984 --rm --name rxdb-couchdb couchdb:2.1.1

stages:
  - install
  - build
  - unit tests
  - code format
  - examples
  - docs
  - other

jobs:
  include:
    - stage: install
      script: travis_retry npm install --depth 0 --silent

    - stage: build
      script: npm run build

    - stage: unit tests
      script: travis_retry npm run test:node
    - stage: unit tests
      script: travis_retry npm run test:fast
    - stage: unit tests
      script: travis_retry npm run test:browser
    - stage: unit tests
      script: travis_retry npm run test:couchdb
    - stage: unit tests
      script: travis_retry npm run test:performance

    - stage: code format
      script: travis_retry npm run test:typings
    - stage: code format
      script: npm run test:deps
    - stage: code format
      script: npm run lint

    - stage: examples
      script: (cd ./examples/angular2 && npm install > "/dev/null" 2>&1 && npm run build && travis_retry npm run test:build)
    - stage: examples
      script: (cd ./examples/vue && npm install > "/dev/null" 2>&1 && npm run lint && npm run build && travis_retry npm run test)
    - stage: examples
      script: (cd ./examples/react-native && npm install > "/dev/null" 2>&1 && travis_retry npm run test)

    - stage: docs
      script: (cd ./test/tutorials/ && npm install --depth 0 --silent && travis_retry npm test)

    - stage: other
      script: npm run build:size
